### ISSUE TITLE
订阅消息

### ISSUE THREAD

**Issue by 00LT00** [00LT00/BigDirectorGo#11]
接收ProjectID,UserID，给除了导演以外的所有人发送，项目即将开始，请相关人员就位
前端@banana-boat

**Comment by Banana-Boat** [comment]
OK！

**Comment by 00LT00** [comment]
[写好了](https://github.com/00LT00/BigDirectorGo#%E7%BB%99%E6%89%80%E6%9C%89%E4%BA%BA%E5%8F%91%E5%BC%80%E5%A7%8B%E6%B6%88%E6%81%AF)
具体内容怎么样到时候慢慢改，但是现在要求项目名称不能超过20

**Comment by Banana-Boat** [comment]
收到！
