### ISSUE TITLE
关于获取项目中所有成员

### ISSUE THREAD

**Issue by mengxun1437** [00LT00/BigDirectorGo#2]
要获取的信息包括，用户的头像，用户的名称，用户的qq，用户的手机号，用户在本项目中的权限，目的是为了用户之间可以通过联系方式私下交流工作，不仅仅是为了查询角色信息

**Comment by mengxun1437** [comment]
在获取到用户信息中，请帮我分组，忘了说了，按照姓氏（例如，张三：group:Z;李四：group：L）

**Comment by 00LT00** [comment]
自己做去
