### ISSUE TITLE
向项目成员推送消息（环节开始、修改）

### ISSUE THREAD

**Issue by Banana-Boat** [00LT00/BigDirectorGo#3]
1. 环节开始提醒
    方式：POST
    参数：
    {
        userid:
        projectid:
        curProc: {
            type: ,
            name: ,（若为type=0，才会有name字段）
            mic: ,
            mic_small: ,
            remark: 
         }
     }
2. 环节修改提醒
    方式：GET
    参数：{{userid}}&{{projectid}}

**Comment by 00LT00** [comment]
第一个做好了

**Comment by 00LT00** [comment]
第二个取消，第一个之前就完成了
