### ISSUE TITLE
获取项目二维码

### ISSUE THREAD

**Issue by Banana-Boat** [00LT00/BigDirectorGo#4]
方式：GET
参数：{{pid}}
返回：arraybuffer类型的二维码

步骤1：
url: 'https://api.weixin.qq.com/cgi-bin/token'
appid: 'wx3e12d5e4462ab875',
secret: '9815f4b527300baff6e7f411c3a15275',
grant_type: 'client_credential'
![image](https://user-images.githubusercontent.com/53339979/82807785-0c42d180-9ebb-11ea-8fcd-ad5ef8256466.png)
  返回：access_token

步骤2：将access_token作为参数获取二维码
url: 'https://api.weixin.qq.com/wxa/getwxacodeunlimit?access_token=' + res.data.access_token,
![image](https://user-images.githubusercontent.com/53339979/82808992-b15ea980-9ebd-11ea-9ab6-c0df35b49417.png)
  返回：arraybuffer类型的二维码

**Comment by 00LT00** [comment]
[已经完成了](https://github.com/00LT00/BigDirectorGo#%E8%8E%B7%E5%8F%96%E9%A1%B9%E7%9B%AE%E4%BA%8C%E7%BB%B4%E7%A0%81)
暂时关闭了，有需求更改到时候再说
