### ISSUE TITLE
实时刷新演出进度

### ISSUE THREAD

**Issue by Banana-Boat** [00LT00/BigDirectorGo#6]
1.导演请求更新当前演出进度

传参：
{
    userid:
    projectID:
    processIndex:
    flag:       //true:正在进行
}

2.其他成员请求读取演出进度

传参：
{
    userid:
    projectID:
}
返回：
{
    processIndex:
    flag:       //true:正在进行
}

**Comment by 00LT00** [comment]
[搞定了](https://github.com/00LT00/BigDirectorGo#%E8%8E%B7%E5%8F%96%E9%A1%B9%E7%9B%AE%E7%8A%B6%E6%80%81)
