### ISSUE TITLE
获取项目环节部分

### ISSUE THREAD

**Issue by mengxun1437** [00LT00/BigDirectorGo#9]
每个环节对应哪个负责人好像没有给出，不希望循环调用，在负责人管理界面的环节打开时，需要看到项目的名称，负责人名称，点击设置的时候，需要拨打电话，可以加的话就加在每个环节里面，不然我每次调用一个接口只为了找到一个电话号码。。。，最最最重要的是要有环节负责人的用户id

**Comment by 00LT00** [comment]
项目名可以加，电话号和qq号这属于用户信息，调接口吧，本身写那个获取信息的接口就是用来让你们实时获取的，结果你们都喜欢一次拿到全部数据存起来用，可问题是大部分人进管理页面并不一定会查看其他人的用户详情，看谁的拿谁的

**Comment by 00LT00** [comment]
[看这个](https://github.com/00LT00/BigDirectorGo#%E7%AE%A1%E7%90%86%E4%BA%BA%E5%91%98-worker)
